# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '11' 
          # Java distribution. See the list of supported distributions in README file
          distribution: 'zulu'

      # Build Maven project
      - name: build
        run: mvn --batch-mode  verify -DskipTests=true
        
      - name: Contrast SCA Action
        uses: Contrast-Security-OSS/contrast-sca-action@main
        with:
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: https://apptwo.contrastsecurity.com
          filePath: .
        
      # Run Contrast Scan
      - name: Contrast Scan Action
        uses: Contrast-Security-OSS/contrastscan-action@v2
        with:
          artifact: target/vulnado-0.0.1-SNAPSHOT.jar
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          apiUrl: https://apptwo.contrastsecurity.com
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          
      # Show SARIF results
      - name: Show SARIF
        run: |
          cat results.sarif

      # Upload the results to GitHub      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
      
      # Verify with Contrast Assess
      - name: Verify with Contrast Assess
        uses: Contrast-Security-OSS/integration-verify-github-action@main
        with: 
          appId: b45efaae-76e9-4b1b-aab9-21cf7ef17cb5
          apiUrl: https://apptwo.contrastsecurity.com
          orgId: f3b61ec4-9959-40c6-93ad-1de953429763
          apiKey: ${{ secrets.CONTRAST2_API_KEY }}
          authHeader: ${{ secrets.CONTRAST2_AUTH_HEADER }}


